# Generated by Django 4.2.6 on 2023-11-14 09:59

from django.db import migrations, models
import main.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64)),
                ('description', models.CharField(max_length=200)),
                ('thumbnail', models.FilePathField(path='static/main')),
                ('text', models.CharField(max_length=4000)),
            ],
        ),
    ]
