# Generated by Django 4.2.6 on 2023-11-15 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_project_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='hyperlink',
            field=models.URLField(blank=True),
        ),
    ]
