# Generated by Django 4.2.6 on 2024-02-01 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0003_project_hyperlink"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="thumbnail",
            field=models.FilePathField(
                path="/home/petmanrea/django-portfolio/portfolio/static/main"
            ),
        ),
    ]
