# Generated by Django 4.2.6 on 2024-02-01 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0004_alter_project_thumbnail"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="thumbnail",
            field=models.FilePathField(path="/static/main"),
        ),
    ]
