# Generated by Django 4.2.6 on 2024-02-01 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0005_alter_project_thumbnail"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="thumbnail",
            field=models.FilePathField(
                path="/home/psetman/django-portfolio/portfolio/static/main"
            ),
        ),
    ]
